name: "Bug report"
description: Report errors or unexpected behavior
labels: [Issue-Bug, Needs-Triage]
body:
- type: markdown
  attributes:
    value: |
      Please make sure to [search for existing issues](https://github.com/sizekcz/krv/issues) and [check the FAQ](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)) before filing a new one!

- type: dropdown
  attributes:
    label: krv version
    options:
      - 1.0.2
      - 1.1.24
      - 1.1.25
      - 1.1.26
      - 1.1.27
      - 1.1.28
      - 1.1.29
      - 1.1.30
      - 1.1.31
      - 1.1.32
      - 1.1.33
### VERSION
  validations:
    required: true
- type: input
  attributes:
    label: Kubernetes distribution and version
    placeholder: "minikube 1.22.3"
    description: |
      Please specify your kubernetes distribution.
  validations:
    required: true

- type: textarea
  attributes:
    label: Deployed validation
    description: Manifest of deployed validation
    placeholder: Validation yaml
    render: shell
  validations:
    required: false

- type: textarea
  attributes:
    label: Steps to reproduce
    placeholder: Tell us the steps required to trigger your bug.
  validations:
    required: false

- type: textarea
  attributes:
    label: Expected Behavior
    description: If you want to include screenshots, paste them into the markdown editor below.
    placeholder: What were you expecting?
  validations:
    required: false

- type: textarea
  attributes:
    label: Actual Behavior
    placeholder: What happened instead?
  validations:
    required: true
