---
name: "Documentation Issue"
description: Report issues in our documentation
labels: Issue-Docs

body:
- type: markdown
  attributes:
    value: |
      Please make sure to [search for existing issues](https://github.com/sizekcz/krv/issues) and [check the FAQ](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)) before filing a new one!

- type: textarea
  attributes:
    label: Documentation Issue
    description: If you want to include screenshots, paste them into the markdown editor below.
  validations:
    required: false
