---
name: "Feature Request/Idea"
about: Suggest a new feature or improvement (this does not mean you have to implement it)
title: ''
labels: Issue-Feature
assignees: ''

---

# Description of the new feature/enhancement


# Proposed technical implementation details (optional)

