---
name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - id: release
      uses: rymndhng/release-on-push-action@master
      with:
        bump_version_scheme: minor

    - name: Check Output Parameters
      run: |
        echo "Got tag name ${{ steps.release.outputs.tag_name }}"
        echo "Got release version ${{ steps.release.outputs.version }}"
        echo "Upload release artifacts to ${{ steps.release.outputs.upload_url }}"


    - name: Build and Push to DockerHub
      uses: MaximilianoBz/dockerhub-buildpush@v1.1
      with:
        registry_url: docker.io
        repository_name: k8s-krv
        user_name: stepanpelc
        password: ${{ secrets.dockerhub_secret }}
        image_version: "${{ steps.release.outputs.tag_name }}"
        
    - name: Push Helm chart to OCI compatible registry (Github)
      uses: bsord/helm-push@v4.1.0
      with:
        useOCIRegistry: true
        registry-url:  oci://registry-1.docker.io/
        username: stepanpelc
        access-token: ${{ secrets.dockerhub_secret }}
        force: true
        chart-folder: helmchart
