---
name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: rymndhng/release-on-push-action@master
      with:
        bump_version_scheme: minor

    - name: Build and Push to DockerHub
      uses: MaximilianoBz/dockerhub-buildpush@v1.1
      with:
        registry_url: docker.io
        repository_name: k8s-krv
        user_name: stepanpelc
        password: ${{ secrets.dockerhub_secret }}
        image_version: ${{ steps.semver.outputs.patch }}

