---
name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # required for github-action-get-previous-tag

    - name: Get previous tag
      id: previoustag
      uses: 'WyriHaximus/github-action-get-previous-tag@v1'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get next minor version
      id: semver
      uses: 'WyriHaximus/github-action-next-semvers@v1'
      with:
        version: ${{ steps.previoustag.outputs.tag }}

    - name: Create release
      id: create_release_id
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.semver.outputs.patch }}
        release_name: Release ${{ steps.semver.outputs.patch }}

    - name: Build and Push to DockerHub
      # You may pin to the exact commit or the version.
      # uses: MaximilianoBz/dockerhub-buildpush@372110d600041736063b948d05005b6039d8fb0c
      uses: MaximilianoBz/dockerhub-buildpush@v1.1
      with:
        # Docker Registry Url, eg: docker.io
        registry_url: docker.io
        # Docker Image Repository Name, eg: username/demo-app
        repository_name: k8s-krv
        # Docker Login UserName, from: https://hub.docker.com/
        user_name: stepanpelc
        # Docker Login Access Token, from: https://hub.docker.com/
        password: ${{ secrets.dockerhub_secret }}
        # Image Build Version
        image_version: 1.0.0
        # Docker File Directory, Default Current Directory (.)
        # docker_file: # optional, default is .
