---
name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v0.1.14
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        target_commitish: ${{ github.ref }}
        tag_name: ${{ github.event.inputs.tag_name }}
        name: ${{ github.event.inputs.release_name }}
        body: ${{ github.event.inputs.release_notes }}
        draft: false
        prerelease: false

    - name: Build and Push to DockerHub
      uses: MaximilianoBz/dockerhub-buildpush@v1.1
      with:
        registry_url: docker.io
        repository_name: k8s-krv
        user_name: stepanpelc
        password: ${{ secrets.dockerhub_secret }}
        image_version: ${{ steps.semver.outputs.patch }}

